### PR TITLE
feat: implement type casting, Agtype to int4[]

### PR DESCRIPTION
**Pull request by emotionbug**
Will be fix, https://github.com/apache/incubator-age/issues/106

### CODE REVIEW

**Comment by JoshInnis** [comment]
needs to be updated to use the age--0.6.0.sql file

**Comment by JoshInnis** [comment]
I pulled your fork and tested out the feature. Looks good, sorry we overlooked it, Could you please merge with master so the merge error is resolved.

**Comment by emotionbug** [comment]
Sorry i missed this comments. I'll do it.

**Review by jrgemignani — APPROVED** [review]
Looks good

**Pull request merged**
